Fix build-time errors with recent dash as sh
dash and FreeBSD sh's "test" builtins do not support the == operator,
leading to confusion at configure time:

  checking for GTHREAD... yes
  ./configure: 13717: test: xyes: unexpected operator
  ./configure: 14011: test: xyes: unexpected operator
[...]
  checking pty.h usability... yes

and errors at compile time:

  make[3]: Entering directory `/home/jrn/src/seed/modules/canvas'
    CC     libseed_canvas_la-seed-canvas.lo
  seed-canvas.c:21:19: fatal error: cairo.h: No such file or directory
  compilation terminated.

Use the more portable = instead.

Probably this was not noticed before because until recently dash
lacked support for $LINENO, leading autoconf to fall back on bash.

Reported-by: Lucas Nussbaum <lucas@lucas-nussbaum.net>
Signed-off-by: Jonathan Nieder <jrnieder@gmail.com>